### ISSUE TITLE
Escape HTML?

### ISSUE THREAD

**Issue by krlmlr** [r-lib/ansistrings#19]
Is the following behavior intended? If the input is colored terminal text, we might want to escape the HTML, but I'm not sure about the dependencies this adds.

``` r
unclass(ansistrings::ansi_to_html("<tag>", fullpage = FALSE))
#> [1] "<tag>"
```

> Created on 2018-02-27 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by gaborcsardi** [comment]
Yes. It only converts the ansi sequences, it does not touch the rest.
